### ISSUE TITLE
configurar projeto

### ISSUE THREAD

**Issue by itsfernandaao** [mbe-co/farmers_app#1]
- criar dockerfile
- criar docker-compose
- configurar rspec
- configurar rubocop
- adicionar coverage

**Comment by itsfernandaao** [comment]
sdds do gitlab. perdida nessas coisas aqui. e cade o pull request? @emilyfaccin

**Comment by emilyfaccin** [comment]
Projeto configurado com serviço de bd
rspec
rubocop
rubycritic
