### ISSUE TITLE
criar model customer

### ISSUE THREAD

**Issue by itsfernandaao** [mbe-co/farmers_app#2]
- [x] adicionar gem devise
- [x] criar model devise Customer
- [x] adicionar atributos definidos no model Customer
- [x] fazer validação de atributos

**Comment by itsfernandaao** [comment]
como ficaria essa configuração do devise, para o docker? @emilyfaccin 
```ruby
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
````

**Comment by emilyfaccin** [comment]
eu ja adicionei tudo isso aí. só criar o customer
precisa gerar o model dentro do container
