### ISSUE TITLE
adicionar no readme

### ISSUE THREAD

**Issue by itsfernandaao** [mbe-co/farmers_app#33]
- [x] adicionar no readme que em caso de adição de nova gem, deve-se rodar `farmers setup`
- [x] separar sessão readme para usuário da app e para desenvolvedor/colaborador com o projeto

ps. te dolo emy!

**Comment by emilyfaccin** [comment]
@itsfernandaao eu acho que README é só pra desenvolvedor / colaborador.
O que você acha que pode ter para usuários?
Se for algo do tipo "Como utilizar", sugiro uma seção na Wiki.
Valeu

**Comment by itsfernandaao** [comment]
a é? eu falei no sentido assim. usuario alguem que quisesse baixar o código e rodar. e desenvolvedor por exemplo, precisaria adicionar gems ou coisas assim. e ai teriam "comandos" mais complexos.

**Comment by itsfernandaao** [comment]
pode desconsiderar então a ultima task e mandar brase
